name: Build and deploy Next.js app to Azure Web App - tech0-gen-11-step3-2-node-59

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: tech0-gen-11-step3-2-node-59
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Deployment Package
        run: |
          mkdir -p deploy_package
          # frontend フォルダの全ソースコードをコピー
          cp -r ./frontend/. ./deploy_package/
          
          # 重い node_modules や以前のビルド成果物は削除して ZIP を軽くする
          rm -rf deploy_package/node_modules
          rm -rf deploy_package/.next
          
          cd deploy_package
          zip -r ../app.zip .
          cd ..

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app-zip
          path: ./app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app-zip
          path: .

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3 
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D939D61B8137457EBCA6E559E44599F2 }}
          package: ./app.zip
